services:
  web:
    build: .
    depends_on:
      - bddsql
      - bddnosql
    container_name: Les 4 Gourmands
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
    environment: 
      - ALLOW_OVERRIDE=true
      - DB_HOST=bddsql
      - DB_USER=creer
      - DB_PASSWORD=boulangerie
      - DB_NAME=Les 4 Gourmands
      # - MA_MOYENNE_VARIABLE=bidule
    restart: always


  bddsql:
    image: mariadb
    ports:
      - "3322:3306"
    environment:
      - MARIADB_ROOT_PASSWORD=root
      - ALLOW_OVERRIDE=true
      - DB_HOST=bddsql
      - DB_USER=creer
      - DB_PASSWORD=boulangerie
      - DB_NAME=les 4 gourmands
    container_name: serverMaria
    restart: always
    
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    ports:
      - "809:80"
    container_name: serverPHPMyAdmin2025
    restart: unless-stopped
    depends_on:
      - bddsql
    environment:
      PMA_HOST: bddsql
      PMA_USER: root
      PMA_PASSWORD: root

  bddnosql:
      image: mongo 
      container_name: serverMongoDB2025
      ports:
        - "27018:27018"
      restart: always
