
version: "3.8"

services:
  web:
    build: .
    depends_on:
      - bddsql
      - bddnosql
    container_name: Les4Gourmands
    ports:
      - "8089:80"
    volumes:
      - .:/var/www/html
    environment: 
      - ALLOW_OVERRIDE=true
      - DB_HOST=bddsql
      - DB_USER=creer
      - DB_PASSWORD=boulangerie
      - DB_NAME=Les4Gourmands
      # - MA_MOYENNE_VARIABLE=bidule
    restart: always
